### ISSUE TITLE
Left OR Right joystick, but not both?

### ISSUE THREAD

**Issue by mano1979** [dmadison/ArduinoXInput_AVR#13]
If i disconnect the left joystick, the right one is working. But if i connect both, the right one doesn't do anything.
It doesn't seem to be a hardware problem, since both were working at one time or another.

**Comment by dmadison** [comment]
Hello. To rule out a hardware problem, please test using pre-programmed numbers not connected to any external hardware. The `SimulateAll` example from the library is a good way to test all of the controls at once.

If that example works without issue, then you must have a hardware problem.

**Comment by mano1979** [comment]
Ok, i tried that and that seems to work fine. Both joysticks are working.

I attached a schematic of the circuit i'm using. To rule out any hardware issues. Hope you can have a look at it
![viber_image_2022-01-26_18-50-13-342](https://user-images.githubusercontent.com/16356475/151218956-2b64609c-927a-4e30-a5e7-928d2dc5ac93.jpg)
.

**Comment by dmadison** [comment]
It looks as though you're missing a wire junction to connect VCC to the joystick's net (center of the schematic, at the bottom). If that schematic was used for a PCB then your problem is there. It's possible that you may have other issues, but it's almost certainly a wiring or hardware fault.

I'm going to close this issue, as your problem appears unrelated to the XInput project. Good luck!

**Comment by mano1979** [comment]
In the schematic the VCC is connected ( i know there is no green dot for the junction, but the connection is actually there) however it seems one of the traces got damaged on the pcb. The VCC trace to be exact. So i manually rewired it and now everything works as it should.

Thank you for your help and quick replies
