### ISSUE TITLE
No compiled .zip for 1.0.1 version

### ISSUE THREAD

**Issue by KulaGGin** [dmadison/ArduinoXInput_AVR#7]
You created a release but forgot to include compiled assets:
![chrome_Jnh2qYMR9V](https://user-images.githubusercontent.com/16989713/73778594-23d33e80-4794-11ea-9d9b-def87fc5c2de.png)

**Comment by dmadison** [comment]
Good catch, thanks. The release is now updated.

For future reference, there's nothing compiled in the repository. The zip just puts the repository into an "xinput/avr" folder so it can be dropped into the Arduino files without the user having to make the folders themselves. It's just a small convenience, which is why I forgot that I did it for the initial release.
