### ISSUE TITLE
Is it possible to rename the device?

### ISSUE THREAD

**Issue by febs** [dmadison/ArduinoXInput_AVR#8]
When I plug in my board with the Xinput AVR it is recognized by Linux as a "Microsoft X-Box 360 pad".

I'd like to know if I can choose to rename each of my devices however I want so to be able to distinguish them in some way (and configure them separately according to their ID).
Thanks

**Comment by dmadison** [comment]
That depends on what the operating system supports.

You cannot change their top level "ID" (VID/PID combination) otherwise the driver won't pick up the board as an Xbox 360 controller. In my experience you *can* change the device strings without causing any issues with the driver, but that also doesn't scream "I'm a totally different device" to the operating system since it uses the same VID and PID. At least on Windows, changing the "name" for one device will also change the "name" for all other devices sharing that VID/PID combo.

Change one of the USB strings to make it unique (`STRING_SERIAL` would be best, `USB_PRODUCT` would be easiest), then you'll have to test for yourself with whichever Linux distro you're using.

**Comment by febs** [comment]
Thank you so much.
